backend:
  name: git-gateway
  branch: master

media_folder: 'src/assets/images/uploads' # Folder where user uploaded files should go
public_folder: 'assets/images/uploads'
publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: 'news' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'News' # Used in the UI, ie.: "New Post"
    folder: 'mdnews' # (src/assets/blog) The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: 'Title',
          name: 'title',
          widget: 'string',
          required: false
        }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          required: false,
        }
      - {
          label: 'Publish',
          name: 'publish',
          widget: 'boolean',
          required: false,
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown'
        }
      - {
          label: 'Publish Date',
          name: 'publishDate',
          widget: 'date',
          format: 'MMM d, y'
        }
